[package]
name = "professional_networking"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "1.9.8"
borsh = "0.9.2"

[dependencies]
spl-token = { version = "3.2.0", features = ["no-entrypoint"] }
solana-program = "1.7.8"
borsh = "0.9.1"
borsh-derive = "0.9.1"
